# Data Science and Machine Learning

## Working of Forward and Backward propagation

In [25]:
import numpy as np
from tqdm import tqdm

In [36]:
class MLP:
    def __init__(self, input_size, hidden_size, output_size):
        self.input_size = input_size
        self.hidden_size = hidden_size
        self.output_size = output_size

        self.W1 = np.random.randn(input_size, hidden_size)
        self.W2 = np.random.randn(hidden_size, output_size)

    def sigmoid(self, x):
        return 1/(1+np.exp(-x))

    def sigmoid_derivative(self, x):
        return x * (1-x)

    def forward(self, X):
        self.hidden_layer = self.sigmoid(np.dot(X, self.W1))
        self.output_layer = self.sigmoid(np.dot(self.hidden_layer, self.W2))
        return self.output_layer

    def backword(self, X, y, lr):
        output_error = y - self.output_layer
        output_delta = output_error * self.sigmoid_derivative(self.output_layer)
        
        hidden_error = output_delta.dot(self.W2.T)
        hidden_delta = hidden_error * self.sigmoid_derivative(self.output_layer)

        self.W2 -= self.hidden_layer.T.dot(output_delta) * lr
        self.W1 -= X.T.dot(hidden_delta) * lr


    def train(self, X, y, epochs = 100, lr = 0.1):
        for each in tqdm(range(epochs)):
            self.forward(X)
            self.backword(X, y, lr)

    def predict(self, X):
        self.forward(X)
        return self.output_layer


In [37]:
X = np.array([
    [0, 0], 
    [0, 1], 
    [1, 0], 
    [1, 1]
])
y = np.array([[0], [1], [1], [0]])

In [47]:
mlp = MLP(input_size=2, hidden_size= 10, output_size= 1)

mlp.forward(X)

array([[0.33142652],
       [0.56806482],
       [0.34504755],
       [0.61035192]])

In [54]:
mlp.train(X, y, epochs=100000, lr = 0.001)

100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100000/100000 [00:09<00:00, 10501.69it/s]


In [55]:
mlp.predict(X)

array([[4.77090941e-05],
       [1.24136259e-04],
       [1.60665017e-05],
       [4.60631044e-05]])

# Tensorflow

In [74]:
import tensorflow as tf

In [75]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [90]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split

In [77]:
df = pd.read_csv(r"C:\Users\karki\OneDrive\Desktop\IRIS.csv")

In [78]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [79]:
X = df.drop('species', axis = 1)
y = df["species"].to_numpy()

In [80]:
onehotencoder = OneHotEncoder(sparse_output= False)
encoded_y = onehotencoder.fit_transform(y.reshape(-1, 1))

In [81]:
encoded_y

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [82]:
scaler = StandardScaler()
X_scale = scaler.fit_transform(X)

In [83]:
X_train, X_test, y_train , y_test = train_test_split(X_scale, encoded_y, test_size= 0.2, shuffle= True, stratify= encoded_y, random_state= 42) 

In [84]:
input_shape = X_train.shape[1]
model = Sequential()
model.add(Dense(64, input_shape = (input_shape, ), activation ='relu'))
model.add(Dense(64, activation = "relu"))
model.add(Dense(3, activation= "softmax"))
model.summary()

C:\Users\karki\OneDrive\Desktop\Data-Science-and-Machine-Learning-04\Data-Science-Classes\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_10"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_14 (Dense)                     │ (None, 64)                  │             320 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_15 (Dense)                     │ (None, 64)                  │           4,160 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_16 (Dense)                     │ (None, 3)                   │             195 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 4,675 (18.26 KB)

 Trainable params: 4,675 (18.26 KB)

 Non-trainable params: 0 (0.00 B)

In [85]:
model.compile(optimizer="adam", loss = "categorical_crossentropy", metrics= ['accuracy'])

In [86]:
#training
history = model.fit(x = X_train, y= y_train, batch_size = 16, epochs= 10, verbose= 1)

Epoch 1/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.4908 - loss: 1.0061
Epoch 2/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.7701 - loss: 0.8195 
Epoch 3/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8757 - loss: 0.6622 
Epoch 4/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8162 - loss: 0.5936 
Epoch 5/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8569 - loss: 0.5090 
Epoch 6/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8602 - loss: 0.4408 
Epoch 7/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8598 - loss: 0.3985 
Epoch 8/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8627 - loss: 0.3491 
Epoch 9/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.8245 - loss: 0.3741 
Epoch 10/10
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.8726 - loss: 0.3039 


In [87]:
loss, accuracy = model.evaluate(X_test, y_test)
print(loss)
print(accuracy)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 371ms/step - accuracy: 0.7667 - loss: 0.3631
0.36312147974967957
0.7666666507720947


In [88]:
loss, accuracy = model.evaluate(X_train, y_train)
print(loss)
print(accuracy)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8790 - loss: 0.2760 
0.29285889863967896
0.8666666746139526


In [92]:
model.save("iris_classification.h5")

## Deployment

In [91]:
# user value 
new_inp = np.array([5.6, 0.5, 0.2, 0.78])
new_inp

array([5.6 , 0.5 , 0.2 , 0.78])

In [96]:
import pickle

# Convolutional Neural Network

In [1]:
import tensorflow as tf
from tensorflow.keras.datasets import mnist

In [2]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()

In [3]:
# Normalization Image Data
x_train = x_train.astype('float32')/255
x_test = x_test.astype('float32')/255

# one hot encoding
y_train = tf.keras.utils.to_categorical(y_train, 10)
y_test = tf.keras.utils.to_categorical(y_test, 10)

In [4]:
print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))

Num GPUs Available:  0
