# Introduction to Scikit-Learn (sklearn)

This notebook demonstrares some of the most useful functions of the beautiful Scikit-Learn library.
We will be coverring:

* An end to end scikit-learn workflor
* Getting the Datas ready
* Choose the right algorithm for our problems
* Fit the model and use it to make predictions
* Evaluate the model
* Improve the model
* Save and load a trained model
* Putting it all together!

# An end to end Sckt-learn workflow

### Getting the Data ready

In [5]:
import pandas as pd
import numpy as np

heart_disease = pd.read_csv(r"D:\Torrents\[FreeCourseSite.com] Udemy - Complete Machine Learning & Data Science Bootcamp 2023\9 - Scikitlearn Creating Machine Learning Models\heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [14]:
# target in the data set represents  if the preson had a Heart-Attack or not
# Create X (feature matrix)
X = heart_disease.drop("target", axis = 1)

#Create Y (labels)
y = heart_disease['target']


### Choosing the right model and hypeparameters

Hyperparameters are essentially configuration settings that you define before training a model.
Hyperparameters are like dial in a model that you can use to tune to make it better or worse

In [15]:
!pip install scikit-learn

In [49]:
from sklearn.ensemble import RandomForestClassifier
#  RandomForestClassifier is a Claissification machine learnning model.
clf = RandomForestClassifier()

# We will keep the Default Hyperparameters
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

# Step 1: DATA PROCESSING

## Getting the Data Ready

In [68]:
# Standard Imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

Three main things we have to do:
* Split the data into Features and labels(usually 'X' and 'y')
* Filling or diregarding the missing values
* Converting non-numerical values to numerical values (also Called Feature Encoding)

In [70]:
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [72]:
X = heart_disease.drop('target', axis= 1)
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [76]:
y = heart_disease['target']
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [78]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

In [80]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [89]:
print(f" The total no of dataset we have is in the shape {X.shape} ")
print(f"The parameter in the train_test_split() where test_size = 0.2 means")
print(f"To Train the data we need {X.shape[0]} * 0.8 = {X_train.shape[0]}")
print(f"And to test the tada we use only 0.2 of the data {X.shape[0]} * 0.2 = {X_test.shape[0]}")

 The total no of dataset we have is in the shape (303, 13) 
The parameter in the train_test_split() where test_size = 0.2 means
To Train the data we need 303 * 0.8 = 242
And to test the tada we use only 0.2 of the data 303 * 0.2 = 61


## 1.1  Making sure its all numerical

In [93]:
car_sales = pd.read_csv(r"D:\Torrents\[FreeCourseSite.com] Udemy - Complete Machine Learning & Data Science Bootcamp 2023\9 - Scikitlearn Creating Machine Learning Models\car-sales-extended.csv")
car_sales.head()

Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [96]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [99]:
# split the data

X = car_sales.drop("Price", axis = 1)

y = car_sales['Price']

# Split into Training and Testing

X_train, X_test,  y_train, y_test = train_test_split(X, y, test_size= 0.2)



In [100]:
# Build Machine Learning Model

from sklearn.ensemble import RandomForestRegressor
# this RandomForestRegressor is same as the classifier RandomforestClassifier but it can predict a number

model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: could not convert string to float: 'Honda'

In [104]:

from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]

one_hot = OneHotEncoder()

transformer = ColumnTransformer([("One_hot",
                                 one_hot,
                                 categorical_features
                                 )], remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X


array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [106]:
pd.DataFrame(transformed_X).head()

0    1    2    3    4    5    6    7    8    9    10   11        12
0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   35431.0
1  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  192714.0
2  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0   84714.0
3  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  154365.0
4  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0  0.0  0.0  181577.0

In [111]:
dummies = pd.get_dummies(car_sales[["Make", "Colour", "Doors"]], dtype= "float")
dummies.head()

Doors  Make_BMW  Make_Honda  Make_Nissan  Make_Toyota  Colour_Black  \
0      4       0.0         1.0          0.0          0.0           0.0   
1      5       1.0         0.0          0.0          0.0           0.0   
2      4       0.0         1.0          0.0          0.0           0.0   
3      4       0.0         0.0          0.0          1.0           0.0   
4      3       0.0         0.0          1.0          0.0           0.0   

   Colour_Blue  Colour_Green  Colour_Red  Colour_White  
0          0.0           0.0         0.0           1.0  
1          1.0           0.0         0.0           0.0  
2          0.0           0.0         0.0           1.0  
3          0.0           0.0         0.0           1.0  
4          1.0           0.0         0.0           0.0

In [125]:
np.random.seed(3)
X_train, X_test, y_train, y_test = train_test_split(transformed_X, 
                                                    y, 
                                                    test_size= 0.22)
model.fit(X_train, y_train)


RandomForestRegressor()

In [126]:
model.score(X_train, y_train)

0.9023534273117821

In [127]:
model.score(X_test, y_test)

0.19970322416860775

##  Filling the values that are missing

* Fill them with some value(also known as imputation.
* Remove the samples with missing data altogether.

In [128]:
car_sales_missing = pd.read_csv(r"D:\Torrents\[FreeCourseSite.com] Udemy - Complete Machine Learning & Data Science Bootcamp 2023\9 - Scikitlearn Creating Machine Learning Models\car-sales-extended-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0

In [130]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [132]:
X = car_sales_missing.drop('Price', axis = 1)

y = car_sales_missing['Price']

In [166]:
car_sales_missing["Make"].fillna("missing", inplace = True)

car_sales_missing['Colour'].fillna("missing", inplace = True)

car_sales_missing["Odometer (KM)"].fillna(car_sales_missing["Odometer (KM)"].mean(), inplace = True)

car_sales_missing["Doors"] = car_sales_missing["Doors"].fillna(int(4))



In [167]:
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)     0
Doors             0
Price            50
dtype: int64

In [169]:
# remove rows with missing price value
car_sales_missing.dropna(inplace = True)

In [171]:
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [172]:
# split the data

X = car_sales.drop("Price", axis = 1)

y = car_sales['Price']

# Split into Training and Testing

X_train, X_test,  y_train, y_test = train_test_split(X, y, test_size= 0.2)

In [176]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]

one_hot = OneHotEncoder()

transformer = ColumnTransformer([("One_hot",
                                 one_hot,
                                 categorical_features
                                 )], remainder="passthrough")

transformed_X = transformer.fit_transform(car_sales_missing)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        3.54310e+04, 1.53230e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        1.92714e+05, 1.99430e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        8.47140e+04, 2.83430e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        6.66040e+04, 3.15700e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.15883e+05, 4.00100e+03],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        2.48360e+05, 1.27320e+04]])

In [178]:
# Impute import SimpleImputer yo padhna baki xa

### Fit the model to the data

In [18]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

In [21]:
clf.fit(X_train, y_train);

In [26]:
# make a Prediction
y_preds = clf.predict(X_test)
y_preds

array([0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1], dtype=int64)

### Evaluate the Model

In [28]:
clf.score(X_train, y_train)

1.0

In [29]:
clf.score(X_test, y_test)

0.8360655737704918

In [31]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.89      0.78      0.83        32
           1       0.79      0.90      0.84        29

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61



In [32]:
confusion_matrix(y_test, y_preds)

array([[25,  7],
       [ 3, 26]], dtype=int64)

In [33]:
accuracy_score(y_test, y_preds)

0.8360655737704918

### Improving the model
Trying different amount of n_estimators

In [38]:
np.random.seed(42)

for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    clf = RandomForestClassifier(n_estimators=i).fit(X_train, y_train )
    print(f"Model accuracy on test set: {clf.score(X_test, y_test) * 100}")
    print(" ")

Trying model with 10 estimators...
Model accuracy on test set: 83.60655737704919
 
Trying model with 20 estimators...
Model accuracy on test set: 81.9672131147541
 
Trying model with 30 estimators...
Model accuracy on test set: 81.9672131147541
 
Trying model with 40 estimators...
Model accuracy on test set: 81.9672131147541
 
Trying model with 50 estimators...
Model accuracy on test set: 83.60655737704919
 
Trying model with 60 estimators...
Model accuracy on test set: 80.32786885245902
 
Trying model with 70 estimators...
Model accuracy on test set: 85.24590163934425
 
Trying model with 80 estimators...
Model accuracy on test set: 83.60655737704919
 
Trying model with 90 estimators...
Model accuracy on test set: 85.24590163934425
 


In [39]:
import pickle

pickle.dump(clf, open("random_forest_model.pkl", "wb"))

In [41]:
loaded_model = pickle.load(open("random_forest_model.pkl", "rb"))
loaded_model.score(X_test, y_test)

0.8524590163934426

## Rewriting the codes


In [52]:
import pandas as pd
import numpy as np

heart_disease = pd.read_csv(r"D:\Torrents\[FreeCourseSite.com] Udemy - Complete Machine Learning & Data Science Bootcamp 2023\9 - Scikitlearn Creating Machine Learning Models\heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [54]:
X = heart_disease.drop("target", axis= 1)
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

In [55]:
y = heart_disease['target']

In [56]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

In [57]:
# Fitting the data to the model

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [58]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [59]:
y_preds = clf.predict(X_test)

In [60]:
y_preds

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0], dtype=int64)

In [61]:
clf.score(X_train, y_train)

1.0

In [62]:
clf.score(X_test, y_test)

0.81

In [66]:
np.random.seed(2)

for i in range (10, 100, 10):
    print(f"No of Estimators = {i} ")
    clf = RandomForestClassifier(n_estimators=i)
    clf.fit(X_train, y_train)
    print(f" Score of the Trained at different Estimators {clf.score(X_test, y_test) * 100}")
    print()
    
    

No of Estimators = 10 
 Score of the Trained at different Estimators 83.0

No of Estimators = 20 
 Score of the Trained at different Estimators 80.0

No of Estimators = 30 
 Score of the Trained at different Estimators 84.0

No of Estimators = 40 
 Score of the Trained at different Estimators 81.0

No of Estimators = 50 
 Score of the Trained at different Estimators 81.0

No of Estimators = 60 
 Score of the Trained at different Estimators 81.0

No of Estimators = 70 
 Score of the Trained at different Estimators 82.0

No of Estimators = 80 
 Score of the Trained at different Estimators 81.0

No of Estimators = 90 
 Score of the Trained at different Estimators 83.0



# STEP 2: Choosing the right Algorithm

Some things to note:
* Sklearn refferes to the machine learning models, algorithms as estimators.
* Classification problem- Predicting a category(heart Disease or not). Generally represented by clf or model used as a classification estimator
* Regression problem - predicting a number(selling price of a car)

![Scikit-learn Machine Learning Map](https://scikit-learn.org/stable/_static/ml_map.png)


## Picking a machine learning model for a regression model

Getting the built in data set from the Sklearn, we will be using the California Housing Dataset which is a real world dataset

In [187]:
from sklearn.datasets import fetch_california_housing

housing = fetch_california_housing()

housing_df = pd.DataFrame(housing["data"] , columns = housing["feature_names"])
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  
0        -122.23  
1        -122.22  
2        -122.24  
3        -122.25  
4        -122.25  
...          ...  
20635    -121.09  
20636    -121.21  
20637    -121.22  
20638    -121.32  
20639    -121.24  

[20640 rows x 8 columns]

In [192]:
housing_df["target"] = housing["target"]
housing_df.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  MedHouseVal  target  
0    -122.23        4.526   4.526  
1    -122.22        3.585   3.585  
2    -122.24        3.521   3.521  
3    -122.25        3.413   3.413  
4    -122.25        3.422   3.422

In [196]:
housing_df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  target  
0        -122.23   4.526  
1        -122.22   3.585  
2        -122.24   3.521  
3        -122.25   3.413  
4        -122.25   3.422  
...          ...     ...  
20635    -121.09   0.781  
20636    -121.21   0.771  
20637    -121.22   0.923  
20638    -121.32   0.847  
20639    -121.24   0.894  

[20640 rows x 9 columns]

In [202]:
from sklearn.model_selection import train_test_split
# Import Algorigthm
from sklearn.linear_model import Ridge

# Setup random seed
np.random.seed(42)

# Create the data lable
X = housing_df.drop("target", axis = 1)

y = housing_df["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

model = Ridge()

model.fit(X_train, y_train)

model.score(X_test, y_test)

0.5758549611440127

Lets try an ensemble model( an ensemble is a combination of smaller models to try and make better prediction than just a simple model


In [205]:
from sklearn.ensemble import RandomForestRegressor

np.random.seed(42)

X = housing_df.drop("target", axis = 1)

y = housing_df["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

model = RandomForestRegressor()

model.fit(X_train, y_train)

model.score(X_test, y_test)


0.8065734772187598

## Pickking a machine learning model for a classification model

In [208]:
heart_disease = pd.read_csv(r"D:\Torrents\[FreeCourseSite.com] Udemy - Complete Machine Learning & Data Science Bootcamp 2023\9 - Scikitlearn Creating Machine Learning Models\heart-disease.csv")
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [209]:
from sklearn.svm import LinearSVC

np.random.seed(42)

X = heart_disease.drop("target", axis =1)
y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

clf = LinearSVC()

clf.fit(X_train, y_train)
clf.score(X_test, y_test)

C:\Users\karki\OneDrive\Desktop\Data-Science-and-Machine-Learning-04\Data-Science-Classes\venv\Lib\site-packages\sklearn\svm\_classes.py:31: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(
C:\Users\karki\OneDrive\Desktop\Data-Science-and-Machine-Learning-04\Data-Science-Classes\venv\Lib\site-packages\sklearn\svm\_base.py:1237: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(


0.8688524590163934

In [211]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis = 1)

y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

model = RandomForestClassifier()

model.fit(X_train, y_train)

model.score(X_test, y_test)


0.8524590163934426

# STEP 3 Fit the algorithm/ Model on our Data and use it to make predictions

## Fitting the model to the data

In [212]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis = 1)

y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

model = RandomForestClassifier()

# Fir the Model to the data
model.fit(X_train, y_train)

model.score(X_test, y_test)


0.8524590163934426

In [214]:
X.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

## Make Prediction using a machile learning model

In [216]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)

X = heart_disease.drop("target", axis = 1)

y = heart_disease["target"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2)

model = RandomForestClassifier()

# Fir the Model to the data
model.fit(X_train, y_train)

model.score(X_test, y_test)


0.8524590163934426

In [217]:
model.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [219]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [220]:
y_preads = model.predict(X_test)
np.mean(y_preads == y_test)

0.8524590163934426

In [223]:
model.score(X_test, y_test)

0.8524590163934426

In [224]:
from sklearn.metrics import accuracy_score

In [227]:
accuracy_score(y_test, y_preads)

0.8524590163934426

* Predict with proba() which returns  probabilities of a classification label

In [231]:
model.predict_proba(X_test[:5])

array([[0.89, 0.11],
       [0.49, 0.51],
       [0.43, 0.57],
       [0.84, 0.16],
       [0.18, 0.82]])

In [2]:
import pandas as pd
car_sales_missing = pd.read_csv(r"D:\Torrents\[FreeCourseSite.com] Udemy - Complete Machine Learning & Data Science Bootcamp 2023\9 - Scikitlearn Creating Machine Learning Models\car-sales-extended-missing-data.csv")
car_sales_missing.head()

Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0